services:
    oneall.oa_social_login.listener:
        class: oneall\oa_social_login\event\listener
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }